### ISSUE TITLE
Using sass-list-maps for simple value mapping in mixins?

### ISSUE THREAD

**Issue by sebnitu** [lunelson/sass-list-maps#3]
I've been playing around with this trying to figure out how I would use this in the context of value mapping in mixins. I'm trying to just get the same result I do when just using the ruby-sass compiler. Here's an example:

``` scss
@mixin colors($text: red, $background: lime, $border: blue) {
  color: $text;
  background: $background;
  border-color: $border;
}

$value: blue, lime, red;
.test {
  @include colors($value...);
}

$value-map: (border: red, background: blue);
.test-map {
  @include colors($value-map...);
}
```

Output using ruby-sass:

``` css
.test {
  color: blue;
  background: lime;
  border-color: red;
}

.test-map {
  color: red;
  background: blue;
  border-color: red;
}
```

My question is how can I use sass-list-maps to get the same results? Am I not understanding something?
